USE [master]
ALTER DATABASE SDM SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
BACKUP LOG [SDM] TO  
DISK = N'U:\MSSQL11.MSSQLSERVER\MSSQL\SDM_Log\SDM_Log' 
WITH NOFORMAT, NOINIT,  NAME = N'SDM_LogBackup', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5
RESTORE DATABASE [SDM] FROM  DISK = N'U:\MSSQL11.MSSQLSERVER\MSSQL\Backup\SFTP_Clients\virpindmisdb01\encrypted\SDM.BAK' WITH  FILE = 1,  NOUNLOAD,  STATS = 5

GO
ALTER DATABASE SDM
SET MULTI_USER
WITH ROLLBACK IMMEDIATE
GO